In [27]:
import numpy as np

In [28]:
a =[1,2,3]
b=np.array(a)
print(a)
print(type(a))
print(b)
print(type(b))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [29]:
print(a*3)
print(b*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [30]:
# Rank = 1인 array
a = np.array((1,2,3,4))
print(a)
print(type(a))
print(a.shape)

temp = [[1,2,3],[4,5,6]]
print(temp)
# Rank = 2인 array
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))
print(b.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


- Rank 무엇?

In [31]:
a=np.array([1,2,3,4])
print(a[0],a[1])
a[0]=5
print(a)

b=np.array([[1,2,3],[4,5,6]])
print(b[0])
print(b[0][2])
print(b[0,2])
b[0,2]=7
print(b)

1 2
[5 2 3 4]
[1 2 3]
3
3
[[1 2 7]
 [4 5 6]]


In [32]:
a = np.array([1,2,3,4], float)
print(a)
print(type(a[0]))
print(a.dtype)

b= np.array([1,2,3,4],int)
print(b)
print(type(b[0]))
print(b.dtype)

[1. 2. 3. 4.]
<class 'numpy.float64'>
float64
[1 2 3 4]
<class 'numpy.int32'>
int32


In [33]:
a=np.array([[1,2,3],[4,5,6]])
print(a[0,0])
print(a[0,:])
print(a[:,2])

1
[1 2 3]
[3 6]


In [34]:
mylist = [[1,2,3],[3,4,5]]
myarray = np.array(mylist)
print(myarray[0])
print(myarray.shape)
print("First row: %s" % myarray[0])
print("Last row: %s" % myarray[-1])
print("Specific row and col: %s" % myarray[0,2])
print("Whole col: %s"% myarray[:,2])

[1 2 3]
(2, 3)
First row: [1 2 3]
Last row: [3 4 5]
Specific row and col: 3
Whole col: [3 5]


In [35]:
a=np.array([1,2])
b=np.array([5,6])

a+b

array([6, 8])

In [36]:
a= np.array([1,2,3])
b= np.array([2,5,6])

print(a+b)
print(a-b)
print(a/b)
print(b/a)
print(b//a)
print(b%a)
print(a**b)

[3 7 9]
[-1 -3 -3]
[0.5 0.4 0.5]
[2.  2.5 2. ]
[2 2 2]
[0 1 0]
[  1  32 729]


In [37]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,4,6],[6,8,10]])

print(a+b)
print(a-b)
print(a/b)
print(b/a)
print(b//a)
print(b%a)
print(a**b)

[[ 3  6  9]
 [10 13 16]]
[[-1 -2 -3]
 [-2 -3 -4]]
[[0.5        0.5        0.5       ]
 [0.66666667 0.625      0.6       ]]
[[2.         2.         2.        ]
 [1.5        1.6        1.66666667]]
[[2 2 2]
 [1 1 1]]
[[0 0 0]
 [2 3 4]]
[[       1       16      729]
 [    4096   390625 60466176]]


In [38]:
# array들의 차원 사이즈가 다르면, 에러 발생!
a=np.array([1,2,3])
b=np.array([3,4])

print(a+b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# broadcasting : 배열과 일차원 배열 더하는 경우, 
# 알아서 차원을 맞춰서 더하게 됨.
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([0.1,0.2])
print(a)
print(b)
print(a+b)

[[1 2]
 [3 4]
 [5 6]]
[0.1 0.2]
[[1.1 2.2]
 [3.1 4.2]
 [5.1 6.2]]


In [ ]:
a=np.zeros((2,2))
print(a)
b=np.array([2,3])
print(b)
print(a+b)

# Numpy의 newaxis라는 함수를 이용하여, b를 어떤 방향으로 더할지 정의
print(a+b[np.newaxis,:])
print(a+b[:,np.newaxis])

[[0. 0.]
 [0. 0.]]
[2 3]
[[2. 3.]
 [2. 3.]]
[[2. 3.]
 [2. 3.]]
[[2. 2.]
 [3. 3.]]


In [46]:
a=np.array([-1,2,3,-4])
print(a)
a=np.abs(a)
print(a)

b=np.array([1,4,9])
print(b)
b=np.sqrt(b)
print(b)

import math
c=np.array([math.e,1,2])
print(c)
c=np.log(c)
print(c)

d= np.array([1.1,1.5,1.9])
print(np.floor(d))
print(np.ceil(d))
print(np.rint(d))

[-1  2  3 -4]
[1 2 3 4]
[1 4 9]
[1. 2. 3.]
[2.71828183 1.         2.        ]
[1.         0.         0.69314718]
[1. 1. 1.]
[2. 2. 2.]
[1. 2. 2.]


In [49]:
a = np.array([1,2,3])
for x in a:
    print(x)
    
b=np.array([[1,2],[3,4],[5,6]])   
for x in b:
    print(x) 
for (x,y) in b:
    print(x*y)

1
2
3
[1 2]
[3 4]
[5 6]
2
12
30


In [63]:
a=np.array([1,2,3,4,5])
#합
print('sum')
print(a.sum())
print(np.sum(a))
#곱
print('production')
print(a.prod())
print(np.prod(a))
#최소값과 그의 index
print('min value and its index')
print(a.min())
print(a.argmin())
#최대값과 그의 index
print('max value and its index')
print(a.max())
print(a.argmax())
#평균과 표준편차
print('mean')
print(a.mean())
print('standard deviation')
print(a.std())

sum
15
15
production
120
120
min value and its index
1
0
max value and its index
5
4
mean
3.0
standard deviation
1.4142135623730951


In [64]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [65]:
a_prime =a.T
print(a_prime)

[[1 3 5]
 [2 4 6]]


In [69]:
#1차원 vector, transpose 하면..?
b= np.array([1,2,3,4])
print(b)
#transpose 적용 x
print(b.T)

#그렇다면 행 벡터를 열 벡터로 변환하고 싶다면(꼼수 적용)
b_prime = b.reshape(-1,1)
print(b_prime)
print(b.shape, ' ===> ', b_prime.shape)

[1 2 3 4]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
(4,)  ===>  (4, 1)


0325 실습 완료.